# Generated by Django 5.0.4 on 2024-06-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=50)),
                ('fecha_venc', models.DateField()),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='masteruni.categoria')),
            ],
        ),
    ]
