# Generated by Django 5.0.4 on 2024-06-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id_conjunto', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etiqueta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('descripcion_pieza', models.TextField()),
                ('cantidad_pieza', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masteruni.categoria')),
                ('id_etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masteruni.etiqueta')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaConjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.conjunto')),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.kit')),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.pieza')),
            ],
        ),
    ]
