# Generated by Django 5.0.4 on 2024-06-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0002_conjunto_etiqueta_kit_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='cantidad_minima_pieza',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
